# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.digitransit: debug

# To develop on GitHub Codespaces
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.3
    - 127.0.0.1
    - ::1
